sudo: false
language: python
matrix:
  # Keep up to date with the tox.ini list
  include:
    - python: pypy
      env: TOXENV=pypy
    - python: 3.7
      dist: xenial
      sudo: true
      env: TOXENV=py37
    - python: 2.7
      env: TOXENV=py27
addons:
  apt:
    packages:
      - libraw-bin
install:
  - pip install -r requirements-dev.txt
  - pip install coveralls
script:
  - make docs
  - make test
after_success:
  - coveralls
